---
title: "Bayesian nonparametric inference with inferno"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Bayesian nonparametric inference with inferno}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



This vignette gives an introduction and guide to the kinds of *Bayesian nonparametric inference* that can be done with ***inferno***, by means of a concrete example. It also has the purpose to clarify the terminology used in the ***inferno*** package.

## Before we start

It is of course impossible to summarize this branch of probability theory and of statistics in a couple of sections; you're invited to learn more for instance from the texts given in the [references](#references).

Two extremely important warnings before you follow the example:

- Some terms may sound familiar to you, but keep in mind that they may have quite different meanings from what you're used to. This is especially true of the terms in *italics*. When you see a term in **boldface**, try to understand its meaning from the way it's used, rather than assuming the meaning familiar to you. Unfortunately, different methods and different disciplines use the same terms in different ways.

  In particular keep in mind that the term **probability** does *not* mean **frequency**. 'Probability' means 'plausibility' or 'degree of belief': it is a quantification of a researcher's uncertainty about some possible fact. There is a connection between probability and frequency, but they are not the same. The distinction is important, because one of the main problems in statistical inference is that *we are uncertain about the frequency of something* -- the occurrence of a disease, symptom, or other characteristics -- and our goal is to quantify and reduce that uncertainty as much as possible.

- The example that follows is, like every example, very specific. But try to see the more general, abstract picture behind it, and to see how its general methodology could be applied to research that is more interesting to you. From time to time we shall draw analogies with other examples that may look very different and yet use essentially the same methodology.

\
You're now welcome to open R in your favourite integrated development environment, choose a directory to work in, and test yourself the code that follows. Let's start by loading the ***inferno*** package:


``` r
library(inferno)
```

In our example we shall use data from the `penguins` dataset, included in R version 4.5.0 and above. We shuffle this dataset to erase any particular ordering of its data, and call the new dataset `penguin` (without the final 's'). For your convenience you can download the shuffled dataset as the CSV file [`'penguin_data.csv'`](https://github.com/pglpm/inferno/raw/main/development/downloads/penguin_data.csv). Otherwise you can create such file from R 4.5.0 or above as follows:


``` r
set.seed(50) # replace with your favourite seed number
penguin <- penguins[sample(1:nrow(penguins)), ] # shuffle

write.csvi(penguin, file = 'penguin_data.csv')
```

The utility function `write.csvi()` saves the dataset as a CSV file that respects the [formatting rules required by ***inferno***](#format).

We assume that you now have the `'penguin_data.csv'` file.


## Penguins

We are researchers interested in penguins; specifically the **population** living in the Antarctic islands *Biscoe*, *Dream*, *Torgersen*. Our research questions are not yet precisely defined, but some initial questions of interest are the following. The penguins can be of three species: [*Adélie*](https://www.bas.ac.uk/about/antarctica/wildlife/penguins/adelie-penguin/), [*Chinstrap*](https://www.bas.ac.uk/about/antarctica/wildlife/penguins/chinstrap-penguin/), [*Gentoo*](https://www.bas.ac.uk/about/antarctica/wildlife/penguins/gentoo-penguin/); we'd like to know:

Q1
: What's the overall statistical occurrence of the three species, independently of location or other details? In other words, what is the relative frequency of each species in the population?

Q2
: Do the three species differ, *statistically*, in some physical or geographical characteristic such as sex or island of origin? We say "statistically" because, for instance, there surely are females and males of every species, but it's possible that for one of the species the ratio of females to males is higher than for another species.

Q3
: Is there a physical or geographical characteristic that allows us to make a good guess about a penguin's species? We say "guess" because, for instance, from knowing which island a penguin comes from we can't be 100% sure about that penguin's species.

In order to approach these and other future questions, we decide which set of penguin characteristics we should consider and observe. These characteristics are called the **variates** of the population. This set can be extended or reduced later on. Guided by previous studies, or by some hypotheses we are entertaining, we choose the following variates, each denoted by a short `codeword`:

- Species (`species`)
- Island (`island`)
- Bill (`bill_len`): [the length of a penguin's "beak"](https://allisonhorst.github.io/palmerpenguins/reference/figures/culmen_depth.png) in millimetres
- Bill depth (`bill_dep`): [the depth of a penguin's "beak"](https://allisonhorst.github.io/palmerpenguins/reference/figures/culmen_depth.png) in millimetres
- Flipper length (`flipper_len`): the length of a penguin's "wing" in millimetres
- Body mass (`body_mass`) in grams
- Sex (`sex`)
- Study year (`year`): the year a penguin was observed and measured

We include the last variate because there could be time trends in the values we observe. For instance, a particular species might have more females than males during one year, and vice versa during another year.


### "Population"?

The question of time-trends leads us to more general considerations and questions about statistical research, which unfortunately are often forgotten.

To start with: this "population" which we want to study, how is it defined exactly? What counts as a member of the population, and what doesn't? For example, a seal clearly doesn't count, because it isn't a penguin. A penguin from the Galápagos island doesn't count either, because it isn't from one of the three Antarctic islands we specified. But does a penguin who was alive in the year 1830 count? what about one who will live in those islands in the year 2100? Does a penguin with some kind of notable physical impairment count? Does a penguin who only lived 1 year count? Does a penguin born in the Galápagos island but subsequently transported to the Antarctic islands count?

No matter which research field you work in, you realize that analogous questions appear when you try to define the "population" in some study.

It is practically impossible to specify an exact criterion for membership in a population under study. We may try to cover and delimit as many factors as possible, but there may always appear a new one we didn't think of. There's no "objective" specification of a population: the specification depends on our research purpose -- which often is not precisely specified either. We must therefore always be prepared to further specify the population of our study. In some cases we may even need to modify our previous specification, and thus discard some data or acquire new ones.

The intrinsic and unavoidable problem in the specification of a population has important consequences for the way we observe and measure the population and its variates. We now turn to this problem.

### Sampling

Our questions **Q1**, **Q2**, **Q3** could have *exact statistical answers* if we had a *complete census* of the penguin population; that is, if we went and "measured" the values of the variates in each and every penguin of the population.

To make this point clearer, imagine a slightly different population. Suppose we were interested only in all the penguins alive today on a specific, very small island. The island turns out to have 17 penguins. We check all of them. We find that 6 of these are females, and 11 are males. It's then a fact that 6/17${}\approx{}$35.3% of penguins in this specific population are females, and 64.7% are males. And if someone picked a penguin from this population and asked us to guess its sex, we would give a 35.3% probability to that penguin's being female, and 64.7% to its being male.^[Note the difference between probability and frequency. If an expert colleague tells us "I was able to take a quick look at that penguin, and it looks female to me, though I'm not completely sure", then our *probability* that this specific penguin is female would get higher than 50%. If we observe the penguin and see that it's female, our probability for female would become 100%.  Yet the *frequency* of females in the population is still 35.3%.]

But it is often impractical or impossible to take a complete census. Think of the case were the whole population includes members or variates that will only exist in the future. For this reason we proceed as follows: we observe a **sample** of the whole population, and from the study of this sample we try to infer the statistical properties of the whole population. Our inferences are perforce uncertain: we can't be fully sure about the exact statistical properties of the whole population. The essential point is that our uncertainty is not just a matter of "I don't know" versus "I know":

- we can *quantify* our uncertainty;
- we can *reduce* our uncertainty, sometimes to the point where it becomes almost a certainty.

Some trusted colleagues thus go to the three islands, and examine samples of penguins there, sending back the values they observe. The way they do the sampling would require a deep analysis and discussion, but for the moment we put these aside.

How many samples should our colleagues collect? The short answer is: as many as they can. The more samples we have, the more certain our conclusions will be -- all kinds of conclusions: for instance those that may reveal the presence, as well as those that may reveal the absence, of important associations.

One important feature of Bayesian inference is that *we don't need to choose beforehand when to stop sampling*. We can monitor the results as more and more samples arrive, and stop as soon as the level of certainty about the results is satisfactory. This is possible because in Bayesian inference the *sample size affects only the uncertainty* we have of the ground truth -- association, effect, or other hypothesis -- but *it cannot affect the ground truth itself*. If the truth is that "there is no effect", then this truth will come to light with more and more certainty as we increase the sample size, and no amount of sampling will be able to change this truth.

## First analysis

Imagine that, a while after the sampling begun, our colleagues start sending the collected sample data to us, a little batch at a time. For the moment we assume that the batches are chosen without any systematic order; in particular, their order is unrelated to the time of sampling. We make this assumption in order to avoid trends, which we'll discuss in another vignette.

We receive the first 10 samples from our sampling survey and store them in the file `'penguin_data10.csv'`, respecting the [formatting rules required by ***inferno***](#format):


``` r
datafile <- 'penguin_data10.csv'
write.csvi(penguin[1:10, ], datafile) # write the first 10 samples
```

Here they are:

```
## Error: lazy-load database '/home/pglpm/R/x86_64-pc-linux-gnu-library/4.5/inferno/R/inferno.rdb' is corrupt
## Error: object 'penguin' not found
```

If you generated the `penguin` dataset yourself, then your first 10 samples may be different.

In the data above, samples #1 and #6 have one or more missing variates. But incomplete data are not a problem: inferences can still be performed from them, because Bayesian methods and ***inferno*** automatically perform *imputation* of missing data, and they do so in a principled way (via the marginalization rule of probability theory).

With these datapoints we start our Bayesian nonparametric analysis using ***inferno***! 

There are now two preliminary steps, which we must usually follow to perform an analysis:

1. Determine and prepare the **metadata** about the variates of interest.
2. Perform the general inference about the whole population from the sampled data; we shall call this **learning** from the sample data.

### Metadata preparation

Metadata are "data about the data". They must be provided in a CSV file respecting the [formatting rules](#format), or as a `data.frame`, and consist of around eight pieces of information about the variates of our population:

Variate name (`name`)
: This is a character or string: name of a variate. Different variates should obviously have different names.


Variate type (`type`)
: ***inferno*** can handle three kinds of variates:
    
    - `nominal`: it can take on a finite number of discrete values, which do not have any natural ordering. Examples could be sex or geographical location.
    - `ordinal`: it can take on a finite number of discrete values, which do have a natural ordering. They can be qualitative or numeric. Examples could be the degree of satisfaction of a customer, or the severity of a disease, or a [Likert scale](https://www.britannica.com/topic/Likert-Scale).
    - `continuous`: it can in principle take on an infinite number of continuous values, although they can be discretized or rounded. Examples could be age or weight.
    
    Many other types of variates exist. For example images and audio are also types of variates; but ***inferno*** cannot handle these complex types. A simple type of variate that ***inferno*** cannot properly handle is the *cyclic* one, such as time of day. There are no clear-cut separations between different types of variates; thus it's sometimes difficult to assess the type.


Domain minimum and maximum (`domainmin`, `domainmax`)
: These are numbers, only defined for numeric-ordinal and continuous variates. These metadata are the minimum and maximum value a variate can take on in a given study. For example, in a study about health or employment of adults, a variate *age* might have a minimum of 18 years. In a more general study involving people of all ages, the minimum would be 0. In a health study where people of 90 years or more are pooled together, the maximum would be 90 years. A minimum could also be minus-infinity, and a maximum plus-infinity. Obviously the minimum should be lower than the maximum.
    
    Sometimes the minimum or maximum is not clear-cut. For instance, there is no theoretical maximum on a person's age, although we can consider an age of 300 impossible to reach today. In such cases the maximum or minimum can be taken to be plus or minus infinity.

Interval between values (`datastep`)
: This is a positive number, only defined for numeric-ordinal and continuous variates. It is the separation between consecutive values. For example, in a 1--5 Likert-scale variate, the interval is 1. For an *age* variate expressed in and rounded to years, the interval is 1. For a *length* variate expressed in centimetres and rounded to millimetres, the interval is 0.1.

Inclusion of inimum and maximum (`minincluded`, `maxincluded`)
: These are logical or `yes`/`no`, only defined for continuous variates. They tell whether the minimum and maximum of a continuous variate are themselves possible values or not. Often such extreme values have a special meaning, and this information is important with censored or pooled data. For example, a *length* continuous variate might be expressed in decimetres and reported without rounding, but all lengths above 1 dm might be pooled together into the value "1 dm or more"; in such case we must make sure to state that `maxincluded` is `TRUE` or `"yes"`.

Values (`V1`, `V2`, ...)
: These are characters or strings, only defined for nominal or non-numeric ordinal variates. They are the values that a nominal or ordinal variate can *in principle* take on in the population of interest. Note that they are include not only the values that are observed in a sample, but also those that could be observed in the rest of the population. A nominal or ordinal variate must have at least two distinct values; it wouldn't make much sense to draw inferences about it otherwise. The metadata file can contain further empty **V...** columns.

Why does ***inferno*** need metadata? Because it performs *nonparametric* inference. In other words, it does not assume the frequency distribution of the variates in the whole population to have any specific class of shapes, such as a Gaussians. It tries to extrapolate the frequency distribution of the whole population from the sample data provided. We must therefore provide to it the same general information that we have about the variates, and about any artificial modifications performed on their values, such as rounding or pooling.

In order to prepare the metadata file we can use ***inferno***'s `metadatatemplate()` helper function. This function reads the sample data and prepares a preliminary file containing heuristic *guesses* about the metadata. We must then check and correct this file. The function motivates its guesses and warns about especially uncertain ones. Here is the code to generate a `'penguin_metadata.csv'` file, and the output and warnings of the helper function:


``` r
metadatafile <- 'penguin_metadata.csv'
metadatatemplate(data = datafile, file = metadatafile)
## Analyzing 8 variates for 10 datapoints.
## 
## * "species" variate:
##   -  3 different  values detected:
##  "Adelie", "Chinstrap", "Gentoo" 
##   which do not seem to refer to an ordered scale.
##   Assuming variate to be NOMINAL.
## 
## * "island" variate:
##   -  3 different  values detected:
##  "Biscoe", "Dream", "Torgersen" 
##   which do not seem to refer to an ordered scale.
##   Assuming variate to be NOMINAL.
## 
## * "bill_len" variate:
##   - Numeric values between 36.2 and 54.2 
##   Assuming variate to be CONTINUOUS.
##   - Distance between datapoints is a multiple of 0.1 
##   Assuming variate to be ROUNDED.
##   - All values are positive
##   Assuming "domainmin" to be 0
## 
## * "bill_dep" variate:
##   - Numeric values between 13.7 and 20.8 
##   Assuming variate to be CONTINUOUS.
##   - Distance between datapoints is a multiple of 0.1 
##   Assuming variate to be ROUNDED.
##   - All values are positive
##   Assuming "domainmin" to be 0
## 
## * "flipper_len" variate:
##   - Only 8 different numeric values detected:
## from 186 to 222 in steps of 1 
##   Assuming variate to be ORDINAL.
## 
## * "body_mass" variate:
##   - Only 7 different numeric values detected:
## from 3300 to 4875 in steps of 25 
##   Assuming variate to be ORDINAL.
## 
## * "sex" variate:
##   -  2 different  values detected:
##  "female", "male" 
##   which do not seem to refer to an ordered scale.
##   Assuming variate to be NOMINAL.
## 
## * "year" variate:
##   - Only 3 different numeric values detected:
## from 2007 to 2009 in steps of 1 
##   Assuming variate to be ORDINAL.
## 
## =========
## WARNINGS - please make sure to check these variates in the metadata file:
## 
## * "year" variate appears to have been rounded
## and then transformed to logarithmic scale.
## This may lead to problems in the inference.
## Preferably, transform it back to non-logarithmic scale.
## =========
## 
## Saved proposal metadata file as "penguin_metadata.csv" 
```

The preliminary metadata file created by `metadatatemplate()` looks like this:


```
## Error: lazy-load database '/home/pglpm/R/x86_64-pc-linux-gnu-library/4.5/inferno/R/inferno.rdb' is corrupt
## Error: object 'dat' not found
```

If you generated the `penguin` dataset yourself, then you might obtain different guesses. Try to follow the following guidelines for the present example.

We see that `metadatatemplate()` guessed correctly about the `species`, `island`, `sex` variates: they are of `'nominal'` type, and all their possible values are correctly listed. If any of the possible values are missing from the sample, and therefore missing in the preliminary metadata, then we should add them under the  additional **V...** columns. Note that we can sort the nominal values in any order we please.

Also the `bill_len` and `bill_dep` variates are correct: they are continuous, rounded to the nearest tenth of millimetre, and cannot be less than zero. The absence of **domainmax** values means that the theoretical maximum is plus infinity. We could replace this maximum with something more realistic, for instance `1000` mm or less, but typically this kind of changes do not lead to relevant differences in our inferences. The absence of **minincluded** means that the minimum, `0`, is not a possible value; similarly for **maxincluded**.

The `year` variate is correctly classified as ordinal, with values between 2007 and 2009. If the sampling had a later end date, we would correct the 2009 value. The `year` variate could alternatively be considered continuous and rounded; in the present case this alternative classification wouldn't affect our inferences: ***inferno*** treats this kind of ambiguous cases in the same way.

Also the `sex` variate is correctly guessed: `nominal` type with possible values `'female'` and `'male'`.

\
The guesses about the `flipper_len` and `body_mass` variates are not correct, however: these variates are continuous, with a minimal value of `0` and no maximal value. They are rounded to `1` mm and `25` g (this was correctly guessed).

We must open the preliminary metadata file `'penguin_metadata.csv'` with our favourite editor, and correct and complete the guesses of the helper function. In this case we end up with the following corrected metadata file:


```
## Error: lazy-load database '/home/pglpm/R/x86_64-pc-linux-gnu-library/4.5/inferno/R/inferno.rdb' is corrupt
## Error: object 'dat' not found
```


### "Learning" and extrapolating from the sample data {#learningfirst}

Now comes the essential part of our analysis: from the sample data and the metadata information,***inferno*** will draw inferences about the *whole* population of penguins, including new penguins (from the same population) that we shall observe in the future. Subsequent analyses are based on this main inference. The general theory behind this kind of inference, based on the property of *exchangeability* and related mathematical theorems, is explained in the [references](#references).

This inference is performed by calling the `learn()` function. Its minimal arguments are three: the sample `data`, the `metadata`, and the name `outputdir` of a directory where the inference results should be saved; some additional information will be suffixed to this directory name. We can also give a numeric `seed` argument if we want to reproduce the same output in another run, and a `parallel` argument specifying the number of cores to be used for parallel computation.

This function in fact does Monte Carlo sampling and is computationally expensive. It may take minutes, hours, or days to run, depending on the amount of sample data and the number of variates. In order to speed up its computations, it tries to use any multi-cores capabilities of the machine it runs in, or the number of cores specified in the `parallel` argument (which shouldn't be larger than the number of cores you actually have!).

The output below was obtained from running `learn()` on 4 cores -- *please wait before running this code*, it might take longer time on your computer:


``` r
learnt10 <- learn(
    data = datafile,
    metadata = metadatafile,
    outputdir = 'penguin_inference',
    seed = 16,
    parallel = 4 # how many cores to use for the computation
)
## Registered doParallelSNOW with 4 workers
## Calculating auxiliary metadata
## 
## Learning:  10 datapoints,  8 variates
## 
##  *************************************************** 
##  Saving output in directory
##  penguin_inference-261031T120155-vrt8_dat10_smp3600 
##  *************************************************** 
## Starting Monte Carlo sampling of 3600 samples by 60 chains
## in a space of 1027 (effectively 3851) dimensions.
## Using 4 cores: 60 samples per chain, max 15 chains per core.
## Core logs are being saved in individual files.
## 
## C-compiling samplers appropriate to the variates (package Nimble)
## this can take tens of minutes. Please wait...
## Compiled core 1. Number of samplers: 1078.       
## Estimating remaining time, please be patient...
## Sampling. Core 4 estimated end time: 2026-10-31 12:09
## Finished Monte Carlo sampling.                                 
## Highest number of Monte Carlo iterations across chains: 3600 
## Highest number of used mixture components: 10 
## 
## Checking test data
## ( #1 #3 #4 #5 #6 #7 #8 #9 #10 )
## 
## rel. MC standard error: min: 0.017  max: 0.048  mean: 0.025 
## eff. sample size: min: 430  max: 3500  mean: 2200 
## needed thinning: min: 2  max: 13  mean: 4.1 
## average: min: 1.6e-08  max: 0.12  mean: 0.014 
## 
## Plotting final Monte Carlo traces and marginal samples...
## 
## Total computation time: 4.3 mins 
## Average total time per chain: 0.071 mins 
## Max total memory used: approx 3500 MB
## Max memory used per core: approx 860 MB
## 
## Removing temporary output files.
## Finished.
## 
## 
## Closing connections to cores.
```

The initial output gives a summary of the sample size, number of variates, saving directory, and other computational details. The "`estimated end time`" line is updated from time to time with a better estimate of the computation's end time. Once the computation is finished, some final information about the underlying Monte Carlo computation and time and memory use is provided.^[The Monte Carlo expert will notice that the effective sample size is around 900 or more. The Monte Carlo sampling is designed to stop when 3600 samples have been obtained with an effective sample size of at least 400, or equivalently a relative Monte Carlo standard error under 0.05. This is enough, considering that the statistical uncertainty in the results can be tens or hundreds of times larger than this. The desired number of samples and maximal Monte Carlo standard error can be specified with the `nsamples` and `relerror` arguments.] Note that the inference above, with 10 sample data and 8 variates, took around 4 GB and 5 minutes to complete on 4 cores.

The results of this main inference are now stored in the compressed file `'learn.rds'` (around 30 MB) within the specified output directory. The name of this directory is also saved as the final value of the `learn()` function. We saved this directory name in the `learnt10` variable in the code above, by invoking `learnt10 <- learn(...)`.

For your convenience the object produced by the computation above can be downloaded as the file [`'learnt10.rds'`](https://github.com/pglpm/inferno/raw/main/development/downloads/learnt10.rds). Once you have downloaded it in your working directory you can just invoke


``` r
learnt10 <- 'learnt10.rds'
```
which produces an object `learnt10` (just a string, in this case) which can be used in the following analysis.


## Example of analysis: frequencies of the three penguin species {#prelimQ1}

### Estimating relative frequencies

Consider our first research question **Q1**: what's the overall statistical occurrence of the three species in the whole population? The relative frequencies of the three species in the whole population are unknown to us, so we cannot give a simple answer such as "Adélie: 0.10, Chinstrap: 0.34, Gentoo: 0.56".

Bayesian nonparametrics and ***inferno*** give a first answer to this question in the form of:

- an *estimate* of the whole-population frequency distribution,
- the *uncertainty* of this estimate.

We discuss both in a moment. First let's compute them using the `Pr()` function. For the present question, this function requires three arguments:

- `Y`: a `data.frame` listing the values of the variate we are interested in. In the present case the variate is `species` and the values are 'Adelie', 'Chinstrap', 'Gentoo'.
- `learnt`: the object that points to the computation made with the `learn()` function, discussed in the previous section. In the present case it's `learnt10`.
- Optionally, `parallel` specifies how many cores we should use for the computation.

Here is a way to call the function; the computation should take at most a couple of seconds:


``` r
# # data frame with the variate and values we want to know the frequencies of
Y <- data.frame(species = c('Adelie', 'Chinstrap', 'Gentoo'))

Fspecies10 <- Pr(
    Y = Y,
    learnt = learnt10,
    parallel = 8 # let's use 8 cores
)
## 
## Registered doParallelSNOW with 8 workers
## Error in as.matrix(vtransform(Y, auxmetadata = auxmetadata, Rout = "normalized", : lazy-load database '/home/pglpm/R/x86_64-pc-linux-gnu-library/4.5/inferno/R/inferno.rdb' is corrupt
```

The answer to our question is now contained in the `Fspecies10` object (we chose this name for "`F`requency distribution of `species`, estimated from `10` samples"). The estimate and its uncertainty can be immediately visualized by calling `plot()` with this object:


``` r
plot(Fspecies10)
## Error: object 'Fspecies10' not found
```

The x-axis of this plot shows the three possible values of the `species` variate. The y-axis reports fractions which may be read as *frequencies* or *probabilities*.

The estimated frequency distribution for the species is the central, solid red curve with small circles. (You may be used to frequency distributions as histograms, rather than as a broken line like in the plot above. The present visualization is more advantageous when we want to compare several frequency distributions, as we'll do later.)

The three estimated frequencies are Adélie: 0.32, Chinstrap: 0.31, Gentoo: 0.37, and can be read from the `values` element of the `Fspecies10` object:


``` r
Fspecies10$values
## Error: object 'Fspecies10' not found
```

What about the uncertainty of these estimates?

### Uncertainty of the estimates: credibility intervals and probabilities

In Bayesian theory, a compact way of expressing the uncertainty in a quantity is by means of a **credibility interval** with a given probability. For instance, if we say that a particular quantity has a 80%-credibility interval equal to $(0.41, 0.69)$, what we mean is that there's an 80% probability that the true value of that quantity is between $0.41$ and $0.69$ -- pretty straightforward! (*Please be careful not to confuse the Bayesian credibility interval with a "confidence interval"*: the latter has a much more involved and less straightforward meaning.)

The `Pr()` function by default calculates two credibility intervals for each frequency estimate: a 50% one, and an 89% one. In our present inference, the 50%-credibility intervals are shown in the plot above as the darker grey band, and the 89%-credibility intervals as the lighter grey band. Note that these intervals contain the 50% ones.

For instance, the plot indicates that there's a 50% probability that the relative frequency of all `Adelie` penguins is roughly between 0.25 and 0.4; and an 89% probability that their relative frequency is roughly between 0.3 and 0.45.

For the `Gentoo` species, there's a 50% probability that its relative frequency is roughly between 0.3 and 0.45; and an 89% probability that their relative frequency is roughly between 0.2 and 0.6.

We can Actually do more: we can plot the probabilities of all possible frequencies. To understand this idea, let's ask: what is the relative frequency of Adélie penguins in the whole population? Possible values could be anything between 0 and 1. But some of these values may be more probable than others. If we look at our 10 samples, we see that 3 out of 10 are `Adelie`. So a relative frequency around 0.3 is a little more probable, although there's still a lot of uncertainty because this is just a small sample.

The `Pr()` function has actually calculated, in an approximate way, the probabilities for all possible frequencies of each species. We can plot the probabilities of the frequencies of the `Adelie` species as follows:


``` r
# # select only Adelie
onlyAdelie <- subset(Fspecies10, list(species = 'Adelie'))
## Error: object 'Fspecies10' not found

hist(onlyAdelie, xlim = c(0, 1), legend = 'topright', col = 2)
## Error: object 'onlyAdelie' not found
```

With the `subset()` function we first extract from the `Fspecies10` object only the information pertaining to the `Adelie` species, saving it into the `onlyAdelie` object. Then the `hist()` function plots the probability distribution for all the frequency values. We see that frequencies between 0.2 and 0.4 have highest probability. But the probability distribution is quite wide; even a frequency of 0.6 has some probability. The vertical line indicates the mean of this probability distribution, which we take as our frequency estimate.

The width of this probability distribution reflects our large uncertainty, which in turn comes from the fact that we have only seen a small sample of penguins. We shall see that this uncertainty decreases and we gather more samples.

\
The credibility intervals are calculated from the probability distribution above. They can be quickly obtained from the `quantiles` element of the `Fspecies10` object. For instance, we can read the 89%-credibility intervals as follows:


``` r
Fspecies10$quantiles[, , c('5.5%', '94.5%')]
## Error: object 'Fspecies10' not found
```

<!-- As the name tells, this element actually report the *quantiles* of the probability. For example, look at the `= 25%` output: among other things it says `Adelie 0.227634`. This means that there's a 25% probability that the frequency of Adélie penguins is below $0.227634$, and thus a 75% probability that it's above $0.227634$.
 -->

### A preliminary report on question Q1

We can now give a preliminary answer to our question **Q1**, "what's the overall statistical occurrence of the three species in the whole population?".

A summary answer could be as follows:

> From a sample of 10 penguins, the inference about the relative frequencies of the three species in the full population is as follows:
> 
> Adélie
> : rel. frequency between 0.13 and 0.53, with 89% probability
> 
> Chinstrap
> : rel. frequency between 0.13 and 0.52, with 89% probability
> 
> Gentoo
> : rel. frequency between 0.18 and 0.59, with 89% probability

But we can also give a fuller answer by displaying the probability distributions for all three frequencies:


``` r
hist(Fspecies10, legend = 'topright', col = 2:4)
## Error: object 'Fspecies10' not found
```

It's important to keep in mind that the three frequencies must add up to 1, so if our future estimates of some of them increase, then the estimate of some others must decrease.


## Examples of analysis: frequencies on different islands  {#prelimQ2}

### Estimating relative frequencies of species, island-wise

Let's now do a preliminary analysis related to research question **Q2**: do the three species differ, statistically, in some physical or geographical characteristic? This question is still somewhat vague, so let's make it more specific: *Is there any difference in species frequency on the different islands?*

In other words, we want to know whether on some particular island, one or more species appear with relative frequencies different from the others'. It might be that all three species are equally present in each island; or the opposite, each species might be confined in a different island.

The way we proceed is analogous to the one in our [first preliminary analysis](#prelimQ1): we shall calculate estimates of frequencies, their uncertainties, and even their probability distributions. But there's one important difference in the present question: the frequencies we want to infer are about penguins *who live on specific islands* -- say, those who live on Biscoe. An exact statistical answer to this question would be obtained through a complete census of the **subpopulation** or **subgroup** of penguins who live on Biscoe. We are therefore speaking about a **conditional frequencies** and **conditional probabilities**.

Bayesian nonparametrics and ***inferno*** can also draw this kind of inferences. We use again the `Pr()` function, but this time we supply an additional `X` argument, which tells which subpopulations we want to focus on. For simplicity, let's say that we want to focus on penguins living on Biscoe or Dream, that is, those whose `island` variate has the values `'Biscoe` or `'Dream'`. The code is as follows:


``` r
# # data frame with the variate and values of the subpopulations of interest
X <- data.frame(island = c('Biscoe', 'Dream'))

Fspecies10I <- Pr(
    Y = Y,
    X = X, # argument for conditional inferences
    learnt = learnt10,
    parallel = 8 # let's use 8 cores
)
## 
## Registered doParallelSNOW with 8 workers
## Error in as.matrix(vtransform(X, auxmetadata = auxmetadata, Rout = "normalized", : lazy-load database '/home/pglpm/R/x86_64-pc-linux-gnu-library/4.5/inferno/R/inferno.rdb' is corrupt
```

The answer to our question is now contained in the `Fspecies10I` object (we add `I` for "island" to the previous name). The estimates of the frequencies and their uncertainties can again be visualized by calling `plot()`:


``` r
plot(Fspecies10I, col = 5:6)
## Error: object 'Fspecies10I' not found
```

The estimated frequencies for the `Biscoe` subpopulation are shown by the solid yellow curve with small circles; those for the `Dream` subpopulation by the dashed purple curve with small squares. More precise values are contained in the `values` element of the `Fspecies10I` object:


``` r
Fspecies10I$values
## Error: object 'Fspecies10I' not found
```

According to these estimates, on Biscoe there should be a predominance of Gentoo penguins, with lower, roughly equal numbers of Adélie and Chinstrap. On Dream, on the other hand, Gentoo should be the minority, and Chinstrap should be the majority. But how sure are we about these estimates? We see that the 89%-credibility intervals of each frequency are quite wide. Also in this case we can get a better picture by displaying the probability distribution of each frequency, by means of the `hist()` function, and see how much they overlap.

For Biscoe island we find


``` r
# # select only Biscoe
onlyBiscoe <- subset(Fspecies10I, list(island = 'Biscoe'))
## Error: object 'Fspecies10I' not found

hist(onlyBiscoe, xlim = c(0, 1), legend = 'topright', col = 2:4)
## Error: object 'onlyBiscoe' not found
```

Note how, according to these preliminary estimates, the frequencies of Adélie and Chinstrap are very close, around 0.2, and quite different from the frequency of Gentoo, around 0.6. Yet, the probability distributions are wide; each distribution gives a non-zero probability to all three estimates.

**For later, keep in mind the following question: *On Biscoe, are the frequencies of Adélie and Chinstrap different?*** The present estimates show almost no difference, but we are warned about a large uncertainty. Will more sampling data confirm "no difference"?

\
For Dream island we find


``` r
# # select only Dream
onlyDream <- subset(Fspecies10I, list(island = 'Dream'))
## Error: object 'Fspecies10I' not found

hist(onlyDream, xlim = c(0, 1), legend = 'topright', col = 2:4)
## Error: object 'onlyDream' not found
```

Among other things we see here a larger difference in the estimated frequencies of Adélie, around 0.3, and Chinstrap, around 0.45. Still, the probability distributions are wide.

**For later, keep in mind the following question: *On Dream, are the frequencies of Adélie and Chinstrap different?*** The present estimates show a difference, but with large uncertainty. Will more sampling data confirm "difference"?


### A preliminary report on question Q2

The last two plots are a visual answer to our research question: "is there any difference in species frequency on the different islands?", restricted to Biscoe and Dream islands. This answer does not only give estimates, but full probability distributions showing their uncertainties.

A more compact summary can again be given with credibility intervals. We can produce it as follows:


``` r
aperm(
    Fspecies10I$quantiles[, , c('5.5%', '94.5%')],
    c(1, 3, 2)) # change order for better display
## Error: object 'Fspecies10I' not found
```

### Differences from "null-hypothesis testing" and *p*-value methods {#nht}

The reason I asked you to keep in mind the two "frequencies different?" questions is that they will demonstrate important differences between Bayesian nonparametrics and methods based on "null-hypothesis testing" and on *p*-values.

Null-hypothesis testing focuses on trying to answer whether a hypothesis of "equality" is false. An important problem of this approach is that "equality" or "difference" are fuzzy notions. Are the two frequencies 0.35 and 0.40 equal or different? What about 0.39 and 0.40? And what about 0.3999 and 0.4000? Whether two numbers can be considered equal or different depends on a choice of tolerance level, which in turn depends on the context and application. In some cases, frequencies of 0.3 and 0.4 might be considered practically equal; in others, frequencies of 0.39 and 0.40 might be considered very different. The ambiguity about the intended tolerance in null-hypothesis testing is one of the aspects that make "p-hacking" possible: frequencies of 0.3999 and 0.4000 will lead to some difference, in enough large samples.

The Bayesian approach resists this context-dependent and even subjective simplification. Instead it focuses on giving *numerical values* and their uncertainties. One frequency is with 90% probability between 0.38 and 0.39; the other is with 90% probability between 0.40 and 0.43. You can then decide whether this is enough for you, or whether you want to get more stringent bounds by collecting more samples.

\

One problem with *p*-values is that if you re-calculate them anew as new samples arrive, sooner or later you can reach as low a *p*-value as you desire. This procedure is called "optional stopping", and is a form of "*p*-hacking". This is why in using methods based on *p*-values you must declare *beforehand* your sample size, or at least a precise stopping rule.

Bayesian estimates don't suffer from this problem. You can calculate anew the estimates and their uncertainties as new samples arrive. What happens is that the uncertainties decrease, and the estimates converge to their true values. If two quantities have equal true values, then no amount of sampling will lead you to unequal estimates. We shall demonstrate this shortly. This feature keeps you safe and gives you greater flexibility in designing your experiments and in changing strategies along the way.


## More samples

### Updating what we've learnt

The preliminary analysis based on only 10 samples of penguins revealed possible interesting hypotheses -- for example that the relative frequencies of Adélie and Chinstrap penguins are very similar on Biscoe island but somewhat different on Dream island. But at the same time the analysis and hypotheses had very large uncertainties.

Now imagine that our sampling colleagues send us 50 more datapoints, which we add to the 10 we already have. Let's store the 60 datapoints in the file `'penguin_data60.csv'`:


``` r
datafile <- 'penguin_data60.csv'
write.csvi(penguin[1:60, ], datafile) # write the first 60 samples
```

Feel free to take a look at your extended sample data. There may be new datapoints with missing values, but as already discussed this isn't a problem for Bayesian theory and ***inferno***.

Let's now update our inferences with the new sampled data. This is done again with the `learn()` function. *Please wait before running this code*, it might take longer time on your computer:


``` r
learnt60 <- learn(
    data = datafile,
    metadata = metadatafile,
    outputdir = 'penguin_inference',
    seed = 16,
    parallel = 4 # how many cores to use for the computation
)
## Registered doParallelSNOW with 4 workers
## Calculating auxiliary metadata
## 
## Learning:  60 datapoints,  8 variates
## 
##  *************************************************** 
##  Saving output in directory
##  __learn_penguin_60-261031T120159-vrt8_dat60_smp3600 
##  *************************************************** 
## Starting Monte Carlo sampling of 3600 samples by 60 chains
## in a space of 1027 (effectively 16651) dimensions.
## Using 4 cores: 60 samples per chain, max 15 chains per core.
## Core logs are being saved in individual files.
## 
## C-compiling samplers appropriate to the variates (package Nimble)
## this can take tens of minutes. Please wait...
## Compiled core 1. Number of samplers: 1328.       
## Estimating remaining time, please be patient...
## Sampling. Core 1 estimated end time: 2026-10-31 12:17
## Finished Monte Carlo sampling.                                 
## Highest number of Monte Carlo iterations across chains: 14235 
## Highest number of used mixture components: 19 
## 
## Checking test data
## ( #8 #15 #20 #27 #30 #33 #43 #46 #59 )
## 
## rel. MC standard error: min: 0.03  max: 0.064  mean: 0.045 
## eff. sample size: min: 250  max: 1100  mean: 580 
## needed thinning: min: 5  max: 22  mean: 12 
## average: min: 4.9e-09  max: 3.8e-08  mean: 1.6e-08 
## 
## Plotting final Monte Carlo traces and marginal samples...
## 
## Total computation time: 13 mins 
## Average total time per chain: 0.21 mins 
## Max total memory used: approx 3600 MB
## Max memory used per core: approx 900 MB
## 
## Removing temporary output files.
## Finished.
## 
## 
## Closing connections to cores.
```

The calculation with 60 sample data took around 4 GB and 15 minutes on 4 cores.

The results of this updated inference are now stored in the compressed file `'learn.rds'` within the new output directory. For your convenience the object produced by the computation above can be downloaded as the file [`'learnt60.rds'`](https://github.com/pglpm/inferno/raw/main/development/downloads/learnt60.rds). Once you have downloaded it in your working directory, invoke


``` r
learnt60 <- 'learnt60.rds'
```

which we now use to update our analysis.


### Updates in our analysis and hypotheses

In our preliminary analysis we focused on three questions:

- *What's the overall statistical occurrence of the three species in the whole population?*
- *Is there any difference between Adélies and Chinstrap frequencies on Biscoe island?*
- *Is there any difference between Adélies and Chinstrap frequencies on Dream island?*

We can calculate the answers -- frequency estimates, their credible intervals, and their probability distributions -- for the increased sample, using the `Pr()` function [as before](#learningfirst); note that in the `learnt =` argument we must use the new `learnt60` object, which points to the updated inference. Here is the calculation for all three questions:


``` r
# # 'Y' and 'X' were previously defined with:
# # Y <- data.frame(species = c('Adelie', 'Chinstrap', 'Gentoo'))
# # X <- data.frame(island = c('Biscoe', 'Dream'))

Fspecies60 <- Pr(
    Y = Y,
    learnt = learnt60, # updated inference
    parallel = 8 # let's use 8 cores
)
## 
## Registered doParallelSNOW with 8 workers
## Error in as.matrix(vtransform(Y, auxmetadata = auxmetadata, Rout = "normalized", : lazy-load database '/home/pglpm/R/x86_64-pc-linux-gnu-library/4.5/inferno/R/inferno.rdb' is corrupt

Fspecies60I <- Pr(
    Y = Y,
    X = X, # argument for conditional inferences
    learnt = learnt60, # updated inference
    parallel = 8 # let's use 8 cores
)
## 
## Closing connections to cores.
## 
## Registered doParallelSNOW with 8 workers
## Error in as.matrix(vtransform(X, auxmetadata = auxmetadata, Rout = "normalized", : lazy-load database '/home/pglpm/R/x86_64-pc-linux-gnu-library/4.5/inferno/R/inferno.rdb' is corrupt
```

Just like in the preliminary analysis we can use the `plot()` and `hist()` functions to visualize estimates, credibility intervals, and probability distributions.

Consider the first question: overall statistical occurrence of the three species. Let's plot the new estimates and their credibility intervals:


``` r
plot(Fspecies60)
## Error: object 'Fspecies60' not found
```

You may notice that the credibility intervals are now narrower, compared to the initial estimate. Let's actually overlap the plots of the initial and updated inferences, to better see how they updated:


``` r
# # find common y-maximum for correct visual comparison
ymax <- max(Fspecies10$quantiles, Fspecies60$quantiles)
## Error: object 'Fspecies10' not found

plot(Fspecies10, ylim = c(0, ymax), col = 2, lty = 2, lwd = 3, pch = 2)
## Error: object 'Fspecies10' not found
plot(Fspecies60, ylim = c(0, ymax), add = TRUE)
## Error: object 'Fspecies60' not found
legend('top', c('10 samples', '60 samples'),
    col = 2:1, lty = 2:1, pch = 2:1, bty = 'n')
## Error in (function (s, units = "user", cex = NULL, font = NULL, vfont = NULL, : plot.new has not been called yet
```

We notice the following differences, among others:

- The new frequency estimates (circles) for `Adelie` and `Chinstrap` differ by almost 10% from the previous ones (triangles); the estimate for `Gentoo` is almost the same.

- All new estimates are almost or fully within the 50%-credibility intervals of the previous estimates. All of them are fully within the previous 89%-credibility intervals.

- The new credibility intervals are narrower than the previous ones.

These observations demonstrate the [features previously discussed](#nht): as the sample size increases, the uncertainty decreases, but without leading to spurious "effects".

We can also plot the updated probability distributions for the relative frequencies of the three species. Let's plot them together with the previous ones, to highlight the changes:


``` r
hist(Fspecies60, legend = 'topright', xlim = c(0, 1),
    col = 2:4, main = '60 samples')
## Error: object 'Fspecies60' not found

hist(Fspecies10, legend = 'topright', xlim = c(0, 1),
    col = 2:4, main = '10 samples')
## Error: object 'Fspecies10' not found
```

We see that in our initial inference (bottom plot) all three probability distributions largely overlapped, indicating our uncertainty on whether any of these frequencies might be very different from the others.

In our updated inference (top plot) there is still a large overlap for the probabilities of `Adelie` and `Gentoo` frequencies, indicating that we're still very uncertain on whether these frequencies might be very different or not -- we need more sample to resolve this. But the probability distribution for the `Chinstrap` frequency has now a smaller overlap with the other two. This indicates an increased probability that this frequency is more different from at least one of the other two.

Our updated quantitative answer to the question "*What's the overall statistical occurrence of the three species in the whole population?*" is as follows:


``` r
Fspecies60$quantiles[, , c('5.5%', '94.5%')]
## Error: object 'Fspecies60' not found
```

> Adélie
> : rel. frequency between 0.29 and 0.49, with 89% probability
> 
> Chinstrap
> : rel. frequency between 0.14 and 0.30, with 89% probability
> 
> Gentoo
> : rel. frequency between 0.30 and 0.50, with 89% probability



### Updates in conditional frequencies

We can quickly repeat the analysis above for the *conditional* frequencies of the `Biscoe` and `Dream` islands, that is, the frequencies for those subpopulations of penguins. Let's plot directly the probability distributions, again together with those of the previous inference.

For `Biscoe` island:


``` r
# # select only Biscoe
onlyBiscoe10 <- subset(Fspecies10I, list(island = 'Biscoe'))
## Error: object 'Fspecies10I' not found
onlyBiscoe60 <- subset(Fspecies60I, list(island = 'Biscoe'))
## Error: object 'Fspecies60I' not found

hist(onlyBiscoe60, legend = 'topright', xlim = c(0, 1),
    col = 2:4, main = '60 samples, Biscoe island')
## Error: object 'onlyBiscoe60' not found

hist(onlyBiscoe10, legend = 'topright', xlim = c(0, 1),
    col = 2:4, main = '10 samples, Biscoe island')
## Error: object 'onlyBiscoe10' not found
```

Notably, we can say that there's an increased probability for a positive answer to our question "*Is there any difference between Adélies and Chinstrap frequencies on Biscoe island?*".

\
For `Dream` island:


``` r
# # select only Dream
onlyDream10 <- subset(Fspecies10I, list(island = 'Dream'))
## Error: object 'Fspecies10I' not found
onlyDream60 <- subset(Fspecies60I, list(island = 'Dream'))
## Error: object 'Fspecies60I' not found

hist(onlyDream60, legend = 'topright', xlim = c(0, 1),
    col = 2:4, main = '60 samples, Dream island')
## Error: object 'onlyDream60' not found

hist(onlyDream10, legend = 'topright', xlim = c(0, 1),
    col = 2:4, main = '10 samples, Dream island')
## Error: object 'onlyDream10' not found
```

Notably, we can say that there's a *decreased* probability for a positive answer to our question "*Is there any difference between Adélies and Chinstrap frequencies on Dream island?*". The two estimates are now closer together.


## Final inferences



**all**



``` r
# # data frame with the variate and values of the subpopulations of interest
X <- data.frame(island = c('Biscoe', 'Dream'))

FspeciesI <- Pr(
    Y = Y,
    X = X, # argument for conditional inferences
    learnt = learnta,
    parallel = 8 # let's use 8 cores
)
## 
## Registered doParallelSNOW with 8 workers
## Error in as.matrix(vtransform(X, auxmetadata = auxmetadata, Rout = "normalized", : lazy-load database '/home/pglpm/R/x86_64-pc-linux-gnu-library/4.5/inferno/R/inferno.rdb' is corrupt
```


``` r
# # select only Biscoe
onlyBiscoe <- subset(FspeciesI, list(island = 'Biscoe'))
## Error: object 'FspeciesI' not found

hist(onlyBiscoe, xlim = c(0, 1), legend = 'topright', col = 2:4)
## Error: object 'onlyBiscoe' not found
```


``` r
# # select only Dream
onlyDream <- subset(FspeciesI, list(island = 'Dream'))
## Error: object 'FspeciesI' not found

hist(onlyDream, xlim = c(0, 1), legend = 'topright', col = 2:4)
## Error: object 'onlyDream' not found
```





\

*(TO BE CONTINUED)*

\

## References {#references}

On *exchangeability*:

- Bernardo, Smith: [*Bayesian Theory*](https://doi.org/10.1002/9780470316870) (repr. 2000). See especially §§ 4.2--4.3, 4.6.

- Dawid: [*Exchangeability and its ramifications*](https://doi.org/10.1093/acprof:oso/9780199695607.003.0002) (2013).

- de Finetti: [*La prévision: ses lois logiques, ses sources subjectives*](https://www.numdam.org/item/AIHP_1937__7_1_1_0) (1937).

- Heath, Sudderth: [*De Finetti's theorem on exchangeable variables*](https://doi.org/10.1080/00031305.1976.10479175) (1976).

- Hewitt, Savage: [*Symmetric measures on Cartesian products*](https://doi.org/10.1090/S0002-9947-1955-0076206-8) (1955).

- Lindley, Novick: [*The role of exchangeability in inference*](https://doi.org/10.1214/aos/1176345331) (1981).

- ***inferno*** accompanying manual: [*Foundations of inference under symmetry*](https://github.com/pglpm/inferno/raw/main/development/manual/optimal_predictor_machine.pdf) (draft).

On Bayesian theory in general:

- Jaynes: [*Probability Theory*](https://doi.org/10.1017/CBO9780511790423) (2003)

- [*ADA 511: Foundations of data science*](https://pglpm.github.io/ADA511)

## Format for data and metadata files and their contents {#format}

The functions of the ***inferno*** package accept CSV files formatted as follows:

- Decimal values should be separated by a *dot*; no comma should be used to separate thousands etc. Example: `86342.75` .
- Character and names should be quoted in single or double quotes. Example: `"female"`.
- Values should be separated by *commas*, not by tabs or semicolons.
- Missing values should be simply *empty*, not denoted by "NA", "missing", "-", or similar.

Names of variates and character variate values should be strings conforming to [R's rules](https://cran.r-project.org/doc/FAQ/R-FAQ.html#What-are-valid-names_003f).

